[package]
name = "rs"
version = "0.1.0"
authors = ["Naoki Oketani <okepy.naoki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
